name: Deploy Patroni to Linode Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        env:
          TF_VAR_github_token: ${{ secrets.LINODE_TOKEN }}
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Set Up Kubeconfig
        run: |
          mkdir -p ~/.kube
          terraform output -raw kubeconfig > ~/.kube/config
          chmod 600 ~/.kube/config
        working-directory: terraform

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Install Helm Charts
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add zalando https://opensource.zalando.com/postgres-operator/charts/postgres-operator
          helm repo update

          # Install ETCD
          helm install etcd bitnami/etcd --set auth.rbac.enabled=false --set replicaCount=1

          # Install Patroni using Zalando PostgreSQL Operator
          helm install postgres-operator zalando/postgres-operator
          helm install postgres-operator-ui zalando/postgres-operator-ui
          
          # Create a PostgreSQL cluster using Zalando Patroni
          cat <<EOF | kubectl apply -f -
          apiVersion: "acid.zalan.do/v1"
          kind: postgresql
          metadata:
            name: patroni-cluster
          spec:
            teamId: "patroni"
            volume:
              size: "1Gi"
            numberOfInstances: 2
            users:
              admin:
                - superuser
                - createdb
              replication:
                - replication
            databases:
              patronidb: admin
            postgresql:
              version: "14"
          
